TYPE: 'DefaultTrainer'
cfg:
  DATALOADER:
    batch_size: 32
    num_workers: 2
  DATASET:
    TYPE: 'SAMPData'
    cfg:
      data_dir: "./datasets/samp/MotionNet"
      valid_batch_size: 32
      is_scheduled_sampling: True
  MODEL:
    TYPE: 'MotionNet'
    cfg:
      state_dim: 647
      I_in_dim: 2048
      I_out_dim: 256
      h_dim: 512
      h_dim_gate: 512
      pred_in_dim: 967
      num_experts: 12
      MoE_layernum: 3
      z_dim: 64
      ENCODER_TYPE: "SAMPEncoder"
      DECODER_TYPE: "SAMPDecoder"
  PIPELINE:
    TYPE: 'VAEPipeline'
    cfg:
      func_wrap_pairs: [["run_step", "sequence_process"]]
      LOSS:
        KLD:
          weight: 0.1
  CRITERION:
    TYPE: "RegressionCriterion"
  OPTIMIZER:
    lr: 0.00005
  SCHEDULE:
    max_epochs: 100
    scheduler:
      TYPE: "LambdaLR"
      lr_lambda: "linear_epoch_func"
  HOOK:
    hook_ss:
      TYPE: "ScheduledSamplingHook"
      priority: 20
      milestones: [30, 60]
    hook_save:
      interval: 10
    hook_eval:
      interval: 10
      test_before_train: False
    hook_resume:
      TYPE: 'ResumeHook'
      priority: 0
  output_dir: 'work_dirs/samp'
